AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  MyRoleName:
    Type: String
Resources:
  SampleRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub ${MyRoleName}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: '*'
